import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from "node:fs";
import path from "node:path";

const rootDir = process.cwd();
const publicDir = path.join(rootDir, "public");
const wwwDir = path.join(rootDir, "www");
const siteDir = path.join(rootDir, "_site");
const logosContentDir = path.join(rootDir, "src", "content", "logos");

const normalize = (p) => p.split(path.sep).join("/");

const astroManagedPages = new Set([
  "404.html",
  "index.html",
  "about.html",
  "search-github.html",
  "search.html",
  "search-other.html",
  "logos/index.html",
  "logos/inventory.html",
  "logos/links.html",
  "logos/metadata.html",
  "logos/missing.html",
  "logos/tags.html",
  "logos/visual.html",
  "report/all-ar21.html",
  "report/all-horizontal.html",
  "report/all-icon.html",
  "report/all-official.html",
  "report/all-tile.html",
  "report/all-wordmark.html",
  "report/colors.html",
  "report/first-letter.html",
  "report/fonts.html",
  "report/icon-vs-favicon.html",
  "report/icon-vs-svgporn.html",
  "report/icon-vs-tile.html",
  "report/inventory.html",
  "report/least-social.html",
  "report/most-social.html",
  "report/notes.html",
  "report/official-vs-all.html",
  "support/index.html",
  "report/index.html",
  "report/metadata.html",
  "report/missing.html",
  "report/tags.html",
  "report/takedown.html",
  "report/tile-vs-supertiny.html",
  "report/unknown-meta.html",
  "report/visual.html",
  "support/contact.html",
  "support/contribute.html",
  "support/credits.html",
  "support/guidelines.html",
  "support/image-sizes.html",
  "support/links.html",
  "support/specification.html",
  "support/tools.html",
  "util/index.html",
  "util/tile-vs-supertiny.html"
]);

const shouldCopyFromWww = (relativePath) => {
  const rel = normalize(relativePath);

  if (!rel || rel === ".") {
    return true;
  }

  if (
    rel.startsWith("_includes/") ||
    rel.startsWith("_layouts/") ||
    rel.startsWith("_plugins/") ||
    rel.startsWith("_data/")
  ) {
    return false;
  }

  if (rel === "_config.yml") {
    return false;
  }

  if (rel.endsWith(".md")) {
    return false;
  }

  if (astroManagedPages.has(rel)) {
    return false;
  }

  return true;
};

const shouldCopyFromSite = (relativePath) => {
  const rel = normalize(relativePath);

  if (!rel || rel === ".") {
    return true;
  }

  // Logos now come from src/content/logos and are generated by Astro.
  if (rel.startsWith("logos/")) {
    return false;
  }

  if (astroManagedPages.has(rel)) {
    return false;
  }

  return true;
};

const shouldCopyFromLogoContent = (relativePath) => {
  const rel = normalize(relativePath);

  if (!rel || rel === ".") {
    return true;
  }

  // Keep markdown in the content collection only; copy assets to /public/logos.
  if (rel.endsWith("/index.md") || rel === "index.md") {
    return false;
  }

  return true;
};

const copyTree = (sourceDir, targetDir, shouldCopy) => {
  if (!existsSync(sourceDir)) {
    return;
  }

  const visit = (currentSource, currentRelative) => {
    const rel = normalize(currentRelative);

    if (!shouldCopy(rel)) {
      return;
    }

    const stats = statSync(currentSource);

    if (stats.isDirectory()) {
      const destination = path.join(targetDir, currentRelative);
      mkdirSync(destination, { recursive: true });

      for (const child of readdirSync(currentSource)) {
        visit(path.join(currentSource, child), path.join(currentRelative, child));
      }
      return;
    }

    const destination = path.join(targetDir, currentRelative);
    mkdirSync(path.dirname(destination), { recursive: true });
    cpSync(currentSource, destination);
  };

  visit(sourceDir, "");
};

rmSync(publicDir, { recursive: true, force: true });
mkdirSync(publicDir, { recursive: true });

copyTree(wwwDir, publicDir, shouldCopyFromWww);
copyTree(siteDir, publicDir, shouldCopyFromSite);
copyTree(logosContentDir, path.join(publicDir, "logos"), shouldCopyFromLogoContent);

console.log("synced public assets for Astro build");
