name: ar21dimensions

on:
  pull_request:
    paths:
      - www/logos/**/*-ar21*.svg
  push:
    paths:
      - www/logos/**/*-ar21*.svg
  workflow_dispatch:

jobs:
  ar21dimensions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install fflint
      run: |
        curl \
          --location \
          --silent \
          https://github.com/FileFormatInfo/fflint/releases/latest/download/fflint_Linux_x86_64.tar.gz \
          | tar -xz fflint

    - name: Check ar21 dimensions
      run: |
        # NOTE: some of the disabled checks are still required, but caught by other CI jobs
        ./fflint svg \
          --foreign=true \
          --height=60 \
          --images=any \
          --namespace=false \
          --progress=false \
          --text=true \
          --width=120 \
          "www/logos/**/*-ar21*.svg"
