name: ar21dimensions

on:
  pull_request:
    paths:
      - www/logos/**/*-ar21*.svg
  push:
    paths:
      - www/logos/**/*-ar21*.svg
  workflow_dispatch:

jobs:
  ar21dimensions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: false

    - name: Install Golang dependencies
      run: go install github.com/FileFormatInfo/fflint/cmd/fflint@latest

    - name: Check ar21 dimensions
      run: |
        # NOTE: some of the disabled checks are still required, but caught by other CI jobs
        fflint svg \
          --foreign=true \
          --height=60 \
          --images=any \
          --namespace=false \
          --progress=false \
          --text=true \
          --width=120 \
          "www/logos/**/*-ar21*.svg"
