name: icondimensions

on:
  pull_request:
    paths:
      - www/logos/**/*-icon*.svg
  push:
    paths:
      - www/logos/**/*-icon*.svg
  workflow_dispatch:

jobs:
  icondimensions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install fflint
      run: |
        curl \
          --location \
          --verbose \
          https://github.com/FileFormatInfo/fflint/releases/latest/download/fflint_Linux_arm64.tar.gz \
          | tar -xz - fflint

    - name: Check icon dimensions
      run: |
        # NOTE: some of the disabled checks are still required, but caught by other CI jobs
        fflint svg \
          --foreign=true \
          --height=64 \
          --images=any \
          --namespace=false \
          --progress=false \
          --text=true \
          --width=64 \
          "www/logos/**/*-icon*.svg"

      

