name: imagecheck

on:
  pull_request:
    paths:
      - www/logos/**/*.svg
  push:
    paths:
      - www/logos/**/*.svg
  workflow_dispatch:

jobs:
  imagecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install fflint
      run: |
        curl \
          --location \
          --verbose \
          https://github.com/FileFormatInfo/fflint/releases/latest/download/fflint_Linux_arm64.tar.gz \
          | tar -xz - fflint

    - name: Check images
      run: bin/chksvgimage.sh

