name: metacheck

on:
  pull_request:
    paths:
      - www/logos/*/index.md
  push:
    paths:
      - www/logos/*/index.md
  workflow_dispatch:

jobs:
  metacheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: false

    - name: Install Golang dependencies
      run: go install github.com/FileFormatInfo/fflint/cmd/fflint@latest

    - name: Check metadata
      run: bin/chkmeta.sh

