name: metacheck

on:
  pull_request:
    paths:
      - www/logos/*/index.md
  push:
    paths:
      - www/logos/*/index.md
  workflow_dispatch:

jobs:
  metacheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install fflint
      run: |
        curl \
          --location \
          --silent \
          https://github.com/FileFormatInfo/fflint/releases/latest/download/fflint_Linux_x86_64.tar.gz \
          | tar -xz fflint

    - name: Check metadata
      run: |
        PATH=.:$PATH bin/chkmeta.sh
